# Версія Docker Compose
version: '3.8'

services:
  # Веб-сервіс (Flask додаток)
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://feedback_user:feedback_password@db:5432/feedback
      - SECRET_KEY=your-secret-key-here
      - POSTGRES_PASSWORD=feedback_password
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # База даних PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: feedback
      POSTGRES_USER: feedback_user
      POSTGRES_PASSWORD: feedback_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U feedback_user -d feedback"]
      interval: 10s
      timeout: 5s
      retries: 5

# Том для збереження даних PostgreSQL
volumes:
  postgres_data: